name = "migrant"
version = "0.2.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Database migrations for SQLite in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "migrant" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.35 or ~> 1.0"
sqlight = "~> 0.9"
simplifile = "~> 1.4"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_erlang = "~> 0.24"
